In [1]:
import numpy as np

```
section1: 3x + 5y = 6 7x - 5y = 9

[3  5]  [6]
[7 -5]  [9]
````

In [2]:

A = np.array([[3, 5], [7, -5]])
B = np.array([6, 9])
X = np.linalg.inv(A).dot(B)

print(X)

[1.5 0.3]


````

section2: x + y + z = 6 y + z = -4 2x + 5y - z = 27

[1  1  1]  [ 6 ]
[0 -1  1]  [-4 ]
[2  5 -1]  [ 27]


````

In [7]:
A = np.array([[1,1,1], [0,1,1], [2,5,-1]])
B = np.array([6,-4,27])
X = np.linalg.inv(A).dot(B)

print(X)


[10.   0.5 -4.5]


````

section3: x + y = 4 2x + 2y = 8

[1  1]  [4]
[2  1]  [8]

````

In [14]:
A = np.array([[1, 1], [2,2]])
B = np.array([4,8])
D = np.linalg.inv(A).dot(B)



print(D)


LinAlgError: Singular matrix

````
An error has occurred "Singular matrix"
 cannot solve a system of equations using a singular matrix (it may have no solution or multiple solutions, but in any case no unique solution)````